import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { getOcrInsightsCategoryLabel } from "./ocrInsightsConfig";
import clsx from "clsx";
const OcrInsightsView = ({ data }) => {
    const totalRows = data.totalRows;
    const hasMissing = data.requiredFields.some((field) => !field.present);
    const hasConflicts = data.conflictGroups.length > 0;
    const documentEntries = Object.entries(data.groupedByDocument).sort(([left], [right]) => left.localeCompare(right));
    return (_jsxs("div", { className: "ocr-insights__content", children: [_jsxs("section", { className: "ocr-insights__section", children: [_jsxs("header", { className: "ocr-insights__section-header", children: [_jsx("h3", { children: "Required Fields Status" }), _jsxs("span", { className: "ocr-insights__section-count", children: [data.requiredFields.length, " fields"] })] }), _jsx("div", { className: "ocr-insights__status-list", children: data.requiredFields.map((field) => (_jsxs("div", { className: clsx("ocr-insights__status-item", {
                                "ocr-insights__status-item--present": field.present,
                                "ocr-insights__status-item--missing": !field.present
                            }), children: [_jsx("span", { className: "ocr-insights__status-icon", "aria-hidden": "true", children: field.present ? "✅" : "⚠️" }), _jsx("span", { className: "ocr-insights__field-label", children: field.label }), _jsx("span", { className: "ocr-insights__status-text", children: field.present ? "Present" : "Missing" })] }, field.fieldKey))) })] }), _jsxs("section", { className: "ocr-insights__section", children: [_jsxs("header", { className: "ocr-insights__section-header", children: [_jsx("h3", { children: "Conflicting Fields" }), _jsxs("span", { className: "ocr-insights__section-count", children: [data.conflictGroups.length, " conflicts"] })] }), hasConflicts ? (_jsxs("div", { className: "ocr-insights__conflict-table", children: [_jsxs("div", { className: "ocr-insights__conflict-row ocr-insights__conflict-row--header", children: [_jsx("span", { children: "Field" }), _jsx("span", { children: "Values" })] }), data.conflictGroups.map((group) => (_jsxs("div", { className: "ocr-insights__conflict-row", children: [_jsx("span", { className: "ocr-insights__field-label", children: group.label }), _jsx("div", { className: "ocr-insights__conflict-values", children: group.values.map((value) => (_jsxs("div", { className: "ocr-insights__conflict-value", children: [_jsx("span", { className: "ocr-insights__conflict-value-doc", children: value.documentName }), _jsx("span", { className: "ocr-insights__value ocr-insights__value--conflict", children: value.value })] }, `${value.documentId}-${value.value}`))) })] }, group.fieldKey)))] })) : (_jsx("div", { className: "drawer-placeholder", children: "No conflicting fields detected." }))] }), _jsxs("section", { className: "ocr-insights__section", children: [_jsxs("header", { className: "ocr-insights__section-header", children: [_jsx("h3", { children: "All Extracted Fields" }), _jsxs("span", { className: "ocr-insights__section-count", children: [totalRows, " fields"] })] }), totalRows === 0 ? (_jsx("div", { className: "drawer-placeholder", children: "No OCR fields extracted yet." })) : (_jsx("div", { className: "ocr-insights__document-list", children: documentEntries.map(([documentType, categories]) => (_jsxs("div", { className: "ocr-insights__document-group", children: [_jsx("div", { className: "ocr-insights__document-title", children: documentType }), Object.entries(categories)
                                    .sort(([left], [right]) => left.localeCompare(right))
                                    .map(([categoryId, rows]) => (_jsxs("div", { className: "ocr-insights__category-group", children: [_jsx("div", { className: "ocr-insights__category-title", children: getOcrInsightsCategoryLabel(categoryId) }), _jsxs("div", { className: "ocr-insights__table", children: [_jsxs("div", { className: "ocr-insights__row ocr-insights__row--header", children: [_jsx("span", { children: "Field" }), _jsx("span", { children: "Value" }), _jsx("span", { children: "Source Document" }), _jsx("span", { children: "Confidence" })] }), rows.map((row) => (_jsxs("div", { className: "ocr-insights__row", children: [_jsx("span", { className: "ocr-insights__field-label", children: row.label }), _jsx("span", { className: clsx("ocr-insights__value", {
                                                                "ocr-insights__value--conflict": row.conflict
                                                            }), children: row.value }), _jsx("span", { className: "ocr-insights__source", children: row.documentName }), _jsx("span", { className: "ocr-insights__confidence", children: row.confidence !== undefined ? row.confidence : "—" })] }, `${row.documentId}-${row.fieldKey}-${row.value}`)))] })] }, categoryId)))] }, documentType))) }))] })] }));
};
export default OcrInsightsView;
