// BF_PORTAL_BLOCK_v522_BROKER_IMPORT
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import fs from "node:fs";
const get=vi.fn(),raw=vi.fn();
vi.mock("@/api",()=>({api:{get:(...a:unknown[])=>get(...a)},rawApiFetch:(...a:unknown[])=>raw(...a)}));
import BrokerDealPanel from "@/components/applications/BrokerDealPanel";
import { categoryLabel, fieldLabel, formatPhone, splitText, statusLabel, validateSplit } from "../brokerImports";
describe("broker import helpers",()=>{it("validates the split like the server",()=>{expect(validateSplit("","","")).toMatch(/percentages or describe/);expect(validateSplit("60","","")).toBe("Enter both percentages.");expect(validateSplit("60","30","")).toMatch(/add up to 100/);expect(validateSplit("60","40","")).toBeNull();expect(validateSplit("","","flat $2,500 to broker")).toBeNull()});it("labels values",()=>{expect(statusLabel("awaiting_client")).toBe("Waiting for client to sign in");expect(fieldLabel("applicant.dob")).toBe("Applicant: Date of birth");expect(categoryLabel("bank_statements_6_months")).toBe("Bank statements (6 months)");expect(splitText({boreal_pct:"60.00",broker_pct:"40.00",terms:null},"Avance")).toBe("Boreal 60% / Avance 40%");expect(formatPhone("+15145550199")).toBe("(514) 555-0199")})});
describe("Deal Confirmation panel",()=>{beforeEach(()=>{get.mockReset();raw.mockReset()});it("warns without split",async()=>{get.mockResolvedValue({deal:null});const onStatus=vi.fn();render(<BrokerDealPanel applicationId="a1" brokerName="Avance" canEdit onStatus={onStatus}/>);expect(await screen.findByText(/Record the commission split before sending/)).toBeTruthy();await waitFor(()=>expect(onStatus).toHaveBeenLastCalledWith(expect.stringMatching(/Avance/)))});it("saves and clears block",async()=>{get.mockResolvedValue({deal:null});raw.mockResolvedValue({ok:true,json:async()=>({deal:{boreal_pct:"60.00",broker_pct:"40.00",terms:null,notes:null,agreed_by_broker:"Jeremy",agreed_on:"2026-09-25"}})});const onStatus=vi.fn();render(<BrokerDealPanel applicationId="a1" brokerName="Avance" canEdit onStatus={onStatus}/>);fireEvent.click(await screen.findByTestId("broker-deal-edit"));fireEvent.change(screen.getByLabelText(/Boreal %/),{target:{value:"60"}});fireEvent.click(screen.getByTestId("broker-deal-save"));expect(await screen.findByText("Boreal 60% / Avance 40%")).toBeTruthy();expect(JSON.parse((raw.mock.calls[0] as any[])[1].body)).toMatchObject({boreal_pct:60,broker_pct:40});await waitFor(()=>expect(onStatus).toHaveBeenLastCalledWith(null))})});
describe("wiring",()=>{it("adds route, nav and send block",()=>{expect(fs.readFileSync("src/App.tsx","utf8")).toMatch(/path="\/broker-imports" element=\{<Navigate to="\/settings\/broker-files"/);expect(fs.readFileSync("src/pages/settings/SettingsPage.tsx","utf8")).toMatch(/id: "broker-files", label: "Broker Files"/);expect(fs.readFileSync("src/layouts/AppLayout.tsx","utf8")).not.toMatch(/Broker Files/);const tab=fs.readFileSync("src/pages/applications/tabs/LendersTab.tsx","utf8");expect(tab).toMatch(/<BrokerDealPanel/);expect(tab).toMatch(/disabled=\{!!brokerBlock \|\| sending/)})});
