// BF_PORTAL_BLOCK_v522_BROKER_IMPORT - pure helpers for partner-broker files (tested).
export type BrokerImportRow = { id:string; broker_name:string; zip_name:string|null; application_id:string|null; applicant_phone:string|null; status:string; summary:{businessName?:string|null; warnings?:string[]; documents?:{name:string;category:string;stored:boolean}[]; notFound?:string[]; client_texted_at?:string|null}|null; /* BF_PORTAL_BLOCK_v531 */ error:string|null; created_at:string; business_name:string|null; boreal_pct:string|number|null; broker_pct:string|number|null; deal_terms:string|null };
export type BrokerDeal = { boreal_pct:string|number|null; broker_pct:string|number|null; terms:string|null; notes:string|null; agreed_by_broker:string|null; agreed_on:string|null };

export function statusLabel(status:string):string {
  switch(status){case "processing":return "Reading files";case "awaiting_client":return "Waiting for client to sign in";case "claimed":return "Client is completing the application";case "failed":return "Import failed";case "discarded":return "Discarded";default:return status;}
}
export function categoryLabel(category:string):string {
  if(category === "other") return "Other (re-file if needed)";
  return category.replace(/_/g," ").replace(/\b6 months\b/,"(6 months)").replace(/^\w/,(c)=>c.toUpperCase());
}
const FIELD_LABELS:Record<string,string>={fundingAmount:"Amount requested",purposeOfFunds:"Use of funds",lookingFor:"Type of financing",businessLocation:"Country",industry:"Industry",yearsInBusiness:"Years in business",annualRevenue:"Annual revenue",monthlyRevenue:"Monthly revenue",accountsReceivable:"Accounts receivable",fixedAssets:"Fixed assets",legalName:"Legal name",businessName:"Operating name",address:"Address",city:"City",state:"Province/State",zip:"Postal code",phone:"Phone",website:"Website",startDate:"Start date",businessStructure:"Business structure",employees:"Employees",craBusinessNumber:"Business number",naicsCode:"NAICS code",firstName:"First name",lastName:"Last name",email:"Email",dob:"Date of birth",street:"Home address",ownership:"Ownership %",title:"Title"};
export function fieldLabel(path:string):string { const [group,key]=path.split("."); const g=group==="kyc"?"Funding":group==="business"?"Business":group==="applicant"?"Applicant":group??""; return `${g}: ${FIELD_LABELS[key??""]??key??path}`; }
export function splitText(deal:{boreal_pct?:string|number|null;broker_pct?:string|number|null;terms?:string|null}|null|undefined,brokerName:string):string|null { if(!deal)return null; const b=deal.boreal_pct==null||deal.boreal_pct===""?null:Number(deal.boreal_pct); const p=deal.broker_pct==null||deal.broker_pct===""?null:Number(deal.broker_pct); if(b!=null&&p!=null)return `Boreal ${b}% / ${brokerName} ${p}%`; return deal.terms||null; }
export function validateSplit(borealPct:string,brokerPct:string,terms:string):string|null { const hasPct=borealPct.trim()!==""||brokerPct.trim()!==""; if(!hasPct&&!terms.trim())return "Enter the split percentages or describe the agreed terms."; if(hasPct){const b=Number(borealPct),p=Number(brokerPct);if(!borealPct.trim()||!brokerPct.trim()||!Number.isFinite(b)||!Number.isFinite(p))return "Enter both percentages.";if(b<0||b>100||p<0||p>100)return "Percentages must be between 0 and 100.";if(Math.abs(b+p-100)>0.01)return "Boreal % and broker % must add up to 100.";} return null; }
export function formatPhone(e164:string|null|undefined):string { const d=String(e164??"").replace(/\D/g,"").slice(-10); return d.length===10?`(${d.slice(0,3)}) ${d.slice(3,6)}-${d.slice(6)}`:(e164??""); }
