// BF_PORTAL_BLOCK_v522_BROKER_IMPORT - import a partner broker's file (one zip per client).
import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, rawApiFetch } from "@/api";
import { categoryLabel, fieldLabel, formatPhone, splitText, statusLabel, type BrokerImportRow } from "./brokerImports";
type ImportResult={applicationId:string;applicantPhone:string|null;businessName:string|null;applicationForm:string|null;documents:{name:string;category:string;stored:boolean;error?:string}[];warnings:string[];prefill:{notFound?:string[]}|null};
const card={background:"var(--surface, #fff)",border:"1px solid var(--border, #e5e7eb)",borderRadius:8,padding:16,marginBottom:16} as const;
const input={padding:"7px 9px",border:"1px solid var(--border, #d1d5db)",borderRadius:6,fontSize:14} as const;
export default function BrokerImportsPage(){
 const [brokerName,setBrokerName]=useState("Avance"),[phone,setPhone]=useState(""),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<ImportResult|null>(null),[rows,setRows]=useState<BrokerImportRow[]>([]),[inputKey,setInputKey]=useState(0);
 const load=useCallback(async()=>{try{const r=await api.get<{imports?:BrokerImportRow[]}>("/api/broker-imports");setRows(r?.imports??[])}catch{/* retain current list */}},[]);useEffect(()=>{void load()},[load]);
 const submit=async()=>{setError(null);setResult(null);if(!file){setError("Choose the client's zip file.");return}if(!/\.zip$/i.test(file.name)){setError("Upload a .zip file (one per client).");return}if(!brokerName.trim()){setError("Enter the broker's name.");return}const fd=new FormData();fd.append("file",file);fd.append("broker_name",brokerName.trim());if(phone.trim())fd.append("applicant_phone",phone.trim());setBusy(true);try{const res=await rawApiFetch("/api/broker-imports",{method:"POST",body:fd});const j:any=await res.json().catch(()=>({}));if(!res.ok){setError(j?.message??j?.error??`Import failed (${res.status}).`);return}setResult((j?.data??j) as ImportResult);setFile(null);setPhone("");setInputKey(k=>k+1);void load()}catch{setError("Import failed. Check your connection and try again.")}finally{setBusy(false)}};
 return <div data-testid="broker-imports-page" style={{padding:20,maxWidth:1100}}><h1>Broker files</h1><p>Upload one zip per client from a partner broker: their completed application plus the documents. The client then signs in with their mobile at client.boreal.financial and finishes a pre-filled application. Nothing goes to lenders until the commission split is recorded on the file.</p>
 <div style={card}><div style={{display:"flex",gap:12,flexWrap:"wrap",alignItems:"flex-end"}}><label>Broker <input style={input} value={brokerName} onChange={e=>setBrokerName(e.target.value)} list="broker-names"/><datalist id="broker-names"><option value="Avance"/></datalist></label><label>Client zip <input key={inputKey} data-testid="broker-zip-input" type="file" accept=".zip,application/zip" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>Client mobile (only if not on the form) <input style={input} inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(514) 555-0199"/></label><button type="button" data-testid="broker-import-submit" disabled={busy} onClick={submit}>{busy?"Reading files... (up to a minute)":"Import"}</button></div>{error&&<div role="alert" style={{color:"#991b1b"}}>{error}</div>}</div>
 {result&&<div data-testid="broker-import-result" style={card}><h2>Imported: {result.businessName??"(business name not found)"}</h2><div>Client mobile: <strong>{result.applicantPhone?formatPhone(result.applicantPhone):"not found"}</strong> - <Link to={`/applications/${result.applicationId}`}>Open the file</Link></div>{result.warnings.length>0&&<ul>{result.warnings.map(w=><li key={w}>{w}</li>)}</ul>}<strong>Documents filed</strong><ul>{result.documents.map(d=><li key={d.name}>{d.name} - {categoryLabel(d.category)}{d.stored?"":` (not saved: ${d.error??"error"})`}</li>)}</ul>{(result.prefill?.notFound?.length??0)>0&&<><strong>Not on the broker's form (the client will be asked)</strong><div>{result.prefill!.notFound!.map(fieldLabel).join(", ")}</div></>}</div>}
 <div style={card}><h2>Recent broker files</h2>{rows.length===0?<div>No broker files yet.</div>:<div style={{overflowX:"auto"}}><table><thead><tr><th>Imported</th><th>Broker</th><th>Business</th><th>Client mobile</th><th>Status</th><th>Split</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} data-testid="broker-import-row"><td>{new Date(r.created_at).toLocaleDateString()}</td><td>{r.broker_name}</td><td>{r.application_id?<Link to={`/applications/${r.application_id}`}>{r.business_name??r.summary?.businessName??"Open file"}</Link>:(r.zip_name??"-")}</td><td>{formatPhone(r.applicant_phone)||"-"}</td><td title={r.error??undefined}>{statusLabel(r.status)}</td><td>{splitText({boreal_pct:r.boreal_pct,broker_pct:r.broker_pct,terms:r.deal_terms},r.broker_name)??<span style={{color:"#991b1b"}}>Not recorded</span>}</td></tr>)}</tbody></table></div>}</div></div>;
}
