import api from "@/api";
export const fetchProfile = () => api.get("/users/me");
export const updateProfile = (payload) => api.patch("/users/me", payload);
export const fetchBranding = () => api.get("/settings/branding");
export const saveBranding = (payload) => api.post("/settings/branding", payload);
export const fetchUsers = () => api.get("/users");
export const createUser = (payload) => api.post("/users", payload);
export const updateUserRole = (id, role) => api.post(`/users/${id}/role`, { role });
export const disableUser = (id) => api.post(`/users/${id}/disable`);
export const enableUser = (id) => api.post(`/users/${id}/enable`);
