// BF_PORTAL_BROKER_PORTAL_v717 - separate broker portal at /broker.
import { useCallback, useEffect, useState } from "react";
import { Navigate, Route, Routes, useNavigate } from "react-router-dom";
import { api, rawApiFetch } from "@/api";
import ReferrerSignupPage from "@/pages/referrer/ReferrerSignupPage";
import ReferrerLoginPage from "@/pages/referrer/ReferrerLoginPage";

type BrokerFile = { import_id:string; application_id:string|null; business_name:string|null; zip_name:string; import_status:string; stage:string|null; created_at:string; boreal_pct:number|null; broker_pct:number|null; terms:string|null; split_status:string|null; broker_counter_pct:number|null; payout_amount:number|null; payout_paid_on:string|null };
const auth = () => ({ Authorization: `Bearer ${sessionStorage.getItem("referrer_token") ?? ""}` });
const money = (v: unknown) => "$" + Number(v ?? 0).toLocaleString("en-CA", { maximumFractionDigits: 2 });
export function stageLabel(f: Pick<BrokerFile,"stage"|"import_status">) { if(f.import_status==="failed") return "Upload could not be read"; if(!f.stage||f.stage==="draft") return "Waiting for the client to sign in"; return f.stage; }

export function SplitBox({f,onDone}:{f:BrokerFile;onDone:()=>void}) {
 const [counter,setCounter]=useState(false), [pct,setPct]=useState(""), [note,setNote]=useState(""), [msg,setMsg]=useState<string|null>(null);
 const send=async(body:Record<string,unknown>)=>{setMsg(null);try{await api(`/api/broker/files/${f.application_id}/split`,{method:"POST",headers:auth(),body:JSON.stringify(body)});onDone();}catch{setMsg("That did not go through. Try again.");}};
 if(!f.split_status)return <span className="text-slate-500">Boreal will propose a split</span>;
 if(f.split_status==="accepted")return <span className="text-green-700">Agreed: you {f.broker_pct??"-"}% / Boreal {f.boreal_pct??"-"}%{f.terms?` (${f.terms})`:""}</span>;
 if(f.split_status==="countered")return <span className="text-slate-700">You proposed {f.broker_counter_pct!==null?`${f.broker_counter_pct}%`:"a new split"}; waiting for Boreal</span>;
 return <div className="space-y-2" data-testid={`split-${f.application_id}`}><div>Boreal proposes: you {f.broker_pct??"-"}% / Boreal {f.boreal_pct??"-"}%{f.terms?` (${f.terms})`:""}</div>{!counter?<div className="flex gap-2"><button className="rounded bg-[#0B1F3A] px-3 py-1 text-white" onClick={()=>{if(window.confirm("Accept this split? It locks for this file."))void send({action:"accept"});}}>Accept</button><button className="rounded border px-3 py-1" onClick={()=>setCounter(true)}>Propose a different split</button></div>:<div className="flex flex-wrap gap-2"><label>Your share %<input aria-label="Your share %" className="ml-1 w-20 border rounded p-1" type="number" min={0} max={100} value={pct} onChange={e=>setPct(e.target.value)}/></label><input aria-label="Note" className="border rounded p-1" value={note} onChange={e=>setNote(e.target.value)}/><button className="rounded bg-[#0B1F3A] px-3 py-1 text-white" disabled={!pct} onClick={()=>void send({action:"counter",broker_pct:Number(pct),note})}>Send</button></div>}{msg&&<div role="alert" className="text-red-700">{msg}</div>}</div>;
}
export function BrokerHome(){
 const navigate=useNavigate(),[files,setFiles]=useState<BrokerFile[]|null>(null),[me,setMe]=useState<{company:string;name:string}|null>(null),[file,setFile]=useState<File|null>(null),[phone,setPhone]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState<string|null>(null),[key,setKey]=useState(0);
 const load=useCallback(async()=>{try{const m=await api<{broker:{company:string;name:string}}>("/api/broker/me",{headers:auth()});setMe(m?.broker??null);const r=await api<{files:BrokerFile[]}>("/api/broker/files",{headers:auth()});setFiles(Array.isArray(r?.files)?r.files:[]);}catch{setFiles([]);setMsg("Could not load your files. If you have not signed the broker agreement yet, finish signing first.");}},[]);
 useEffect(()=>{void load();},[load]);
 const upload=async()=>{if(!file)return setMsg("Choose the client's zip file.");if(!/[.]zip$/i.test(file.name))return setMsg("Upload a .zip file (one per client).");const fd=new FormData();fd.append("file",file);if(phone.trim())fd.append("applicant_phone",phone.trim());setBusy(true);setMsg(null);try{const res=await rawApiFetch("/api/broker/files",{method:"POST",body:fd,headers:auth()});const j=await res.json().catch(()=>({})) as {message?:string;error?:string;businessName?:string};if(!res.ok){setMsg(j.message??j.error??`Upload failed (${res.status}).`);return;}setMsg(`Uploaded${j.businessName?` ${j.businessName}`:""}. Boreal will review it and contact the client for anything missing.`);setFile(null);setPhone("");setKey(k=>k+1);void load();}catch{setMsg("Upload failed. Check your connection and try again.");}finally{setBusy(false);}};
 return <main className="min-h-screen bg-slate-50 p-4"><div className="mx-auto max-w-5xl space-y-4"><header className="flex justify-between"><h1 className="text-xl font-semibold">Broker Portal{me?` - ${me.company}`:""}</h1><button className="underline" onClick={()=>{sessionStorage.removeItem("referrer_token");sessionStorage.removeItem("referrer_user");navigate("/broker/login");}}>Log out</button></header><section className="rounded-lg border bg-white p-4 space-y-2"><h2 className="font-semibold">Send a file</h2><p className="text-sm text-slate-600">One zip per client with their completed application and documents.</p><div className="flex flex-wrap gap-2"><input key={key} aria-label="Client zip file" type="file" accept=".zip" onChange={e=>setFile(e.target.files?.[0]??null)}/><input aria-label="Client mobile (optional)" className="border rounded p-1" value={phone} onChange={e=>setPhone(e.target.value)}/><button className="rounded bg-[#0B1F3A] px-3 py-1 text-white" disabled={busy} onClick={()=>void upload()}>{busy?"Uploading...":"Upload"}</button></div>{msg&&<p role="status">{msg}</p>}</section><section className="rounded-lg border bg-white p-4"><h2 className="font-semibold mb-2">Your files</h2>{files===null?<p>Loading...</p>:files.length===0?<p>No files yet.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>Client</th><th>Sent</th><th>Stage</th><th>Commission split</th><th>Your payout</th></tr></thead><tbody>{files.map(f=><tr key={f.import_id} className="border-t"><td>{f.business_name??f.zip_name}</td><td>{new Date(f.created_at).toLocaleDateString("en-CA")}</td><td>{stageLabel(f)}</td><td>{f.application_id?<SplitBox f={f} onDone={()=>void load()}/>:"-"}</td><td>{f.payout_amount!=null?`${money(f.payout_amount)}${f.payout_paid_on?` paid ${f.payout_paid_on}`:""}`:"-"}</td></tr>)}</tbody></table></div>}</section></div></main>;
}
export default function BrokerPortalRoutes(){const signedIn=Boolean(sessionStorage.getItem("referrer_token"));return <Routes><Route path="signup" element={<ReferrerSignupPage kind="broker"/>}/><Route path="login" element={<ReferrerLoginPage kind="broker"/>}/><Route path="/" element={signedIn?<BrokerHome/>:<Navigate to="/broker/signup" replace/>}/><Route path="*" element={<Navigate to="/broker" replace/>}/></Routes>}
