import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Button from "@/components/ui/Button";
import ErrorBanner from "@/components/ui/ErrorBanner";
import Input from "@/components/ui/Input";
import Modal from "@/components/ui/Modal";
import Select from "@/components/ui/Select";
const LenderProductModal = ({ isOpen, title, isSaving, isSubmitDisabled = false, errorMessage, formValues, formErrors, lenderOptions, categoryOptions, rateTypes, documentOptions, formatRateType, onChange, onSubmit, onClose, onCancel, statusNote }) => {
    if (!isOpen)
        return null;
    return (_jsxs(Modal, { title: title, onClose: onClose, children: [errorMessage && _jsx(ErrorBanner, { message: errorMessage }), statusNote, _jsxs("form", { className: "management-form", onSubmit: (event) => {
                    event.preventDefault();
                    onSubmit();
                }, children: [_jsxs("div", { className: "management-field", children: [_jsx("span", { className: "management-field__label", children: "Core details" }), _jsxs(Select, { label: "Lender", value: formValues.lenderId, onChange: (event) => onChange({ lenderId: event.target.value }), children: [_jsx("option", { value: "", children: "Select lender" }), lenderOptions.map((option) => (_jsx("option", { value: option.value, disabled: option.disabled, children: option.label }, option.value)))] }), formErrors.lenderId && _jsx("span", { className: "ui-field__error", children: formErrors.lenderId }), _jsx(Input, { label: "Product name", value: formValues.productName, onChange: (event) => onChange({ productName: event.target.value }), error: formErrors.productName }), _jsxs("label", { className: "management-toggle", children: [_jsx("input", { type: "checkbox", checked: formValues.active, onChange: (event) => onChange({ active: event.target.checked }) }), _jsx("span", { children: "Active product" })] }), formErrors.active && _jsx("span", { className: "ui-field__error", children: formErrors.active }), _jsx(Select, { label: "Product category", value: formValues.category, onChange: (event) => onChange({ category: event.target.value }), children: categoryOptions.map((option) => (_jsx("option", { value: option.value, disabled: option.disabled, children: option.label }, option.value))) }), formErrors.category && _jsx("span", { className: "ui-field__error", children: formErrors.category }), _jsx("div", { className: "management-grid__row", children: _jsxs("div", { className: "ui-field", children: [_jsx("span", { className: "ui-field__label", children: "Country availability" }), _jsx("div", { className: "management-docs", children: [
                                                { value: "CA", label: "Canada" },
                                                { value: "US", label: "United States" }
                                            ].map((option) => {
                                                const checked = formValues.country.includes(option.value);
                                                return (_jsxs("label", { className: "management-toggle", children: [_jsx("input", { type: "checkbox", checked: checked, onChange: (event) => {
                                                                const next = event.target.checked
                                                                    ? [...formValues.country, option.value]
                                                                    : formValues.country.filter((value) => value !== option.value);
                                                                onChange({ country: next });
                                                            } }), _jsx("span", { children: option.label })] }, option.value));
                                            }) })] }) }), formErrors.country && _jsx("span", { className: "ui-field__error", children: formErrors.country })] }), _jsxs("div", { className: "management-field", children: [_jsx("span", { className: "management-field__label", children: "Amount" }), _jsxs("div", { className: "management-grid__row", children: [_jsx(Input, { label: "Minimum amount", value: formValues.minAmount, onChange: (event) => onChange({ minAmount: event.target.value }), error: formErrors.minAmount }), _jsx(Input, { label: "Maximum amount", value: formValues.maxAmount, onChange: (event) => onChange({ maxAmount: event.target.value }), error: formErrors.maxAmount })] })] }), _jsxs("div", { className: "management-field", children: [_jsx("span", { className: "management-field__label", children: "Terms" }), _jsxs("div", { className: "management-grid__row", children: [_jsx(Input, { label: "Min term (months)", value: formValues.minTerm, onChange: (event) => onChange({ minTerm: event.target.value }), error: formErrors.minTerm }), _jsx(Input, { label: "Max term (months)", value: formValues.maxTerm, onChange: (event) => onChange({ maxTerm: event.target.value }), error: formErrors.maxTerm })] })] }), _jsxs("div", { className: "management-field", children: [_jsx("span", { className: "management-field__label", children: "Pricing & terms" }), _jsx(Select, { label: "Rate type", value: formValues.rateType, onChange: (event) => onChange({ rateType: event.target.value }), children: rateTypes.map((rateType) => (_jsx("option", { value: rateType, children: formatRateType(rateType) }, rateType))) }), formErrors.rateType && _jsx("span", { className: "ui-field__error", children: formErrors.rateType }), _jsxs("div", { className: "management-grid__row", children: [_jsx(Input, { label: formValues.rateType === "variable" ? "Interest min (Prime + X%)" : "Interest min (%)", value: formValues.interestMin, onChange: (event) => onChange({ interestMin: event.target.value }), error: formErrors.interestMin }), _jsx(Input, { label: formValues.rateType === "variable" ? "Interest max (Prime + Y%)" : "Interest max (%)", value: formValues.interestMax, onChange: (event) => onChange({ interestMax: event.target.value }), error: formErrors.interestMax })] })] }), _jsxs("div", { className: "management-field", children: [_jsx("span", { className: "management-field__label", children: "Required documents" }), _jsx("div", { className: "management-docs", children: documentOptions.map((doc) => {
                                    const checked = formValues.requiredDocuments.includes(doc.value);
                                    return (_jsxs("label", { className: "management-toggle", children: [_jsx("input", { type: "checkbox", checked: checked, onChange: (event) => {
                                                    if (doc.locked)
                                                        return;
                                                    const next = event.target.checked
                                                        ? [...formValues.requiredDocuments, doc.value]
                                                        : formValues.requiredDocuments.filter((value) => value !== doc.value);
                                                    onChange({ requiredDocuments: next });
                                                }, disabled: doc.locked }), _jsx("span", { children: doc.label })] }, doc.value));
                                }) })] }), _jsxs("div", { className: "management-actions", children: [_jsx(Button, { type: "submit", disabled: isSaving || isSubmitDisabled, children: isSaving ? "Saving..." : "Save product" }), _jsx(Button, { type: "button", variant: "ghost", onClick: onCancel, disabled: isSaving, children: "Cancel" })] })] })] }));
};
export default LenderProductModal;
