// BF_PORTAL_BLOCK_v522_BROKER_IMPORT - per-file commission split (Deal Confirmation).
import { useEffect, useState } from "react";
import { api, rawApiFetch } from "@/api";
import { splitText, validateSplit, type BrokerDeal } from "@/pages/brokerImports/brokerImports";

type Props={applicationId:string;brokerName:string;canEdit:boolean;onStatus?:(blockMessage:string|null)=>void};
export default function BrokerDealPanel({applicationId,brokerName,canEdit,onStatus}:Props){
 const [deal,setDeal]=useState<BrokerDeal|null>(null),[loaded,setLoaded]=useState(false),[editing,setEditing]=useState(false);
 const [boreal,setBoreal]=useState(""),[broker,setBroker]=useState(""),[terms,setTerms]=useState(""),[agreedBy,setAgreedBy]=useState(""),[agreedOn,setAgreedOn]=useState(new Date().toISOString().slice(0,10)),[notes,setNotes]=useState("");
 const [msg,setMsg]=useState<string|null>(null),[saving,setSaving]=useState(false);
 useEffect(()=>{let alive=true;api.get<{deal:BrokerDeal|null}>(`/api/broker-imports/deal/${encodeURIComponent(applicationId)}`).then(r=>{if(alive){setDeal(r?.deal??null);setLoaded(true);}}).catch(()=>{if(alive)setLoaded(true);});return()=>{alive=false};},[applicationId]);
 useEffect(()=>{if(loaded)onStatus?.(deal?null:`This file came from ${brokerName}. Record the commission split before sending it to lenders.`)},[loaded,deal,brokerName,onStatus]);
 const startEdit=()=>{setBoreal(deal?.boreal_pct!=null?String(Number(deal.boreal_pct)):"");setBroker(deal?.broker_pct!=null?String(Number(deal.broker_pct)):"");setTerms(deal?.terms??"");setAgreedBy(deal?.agreed_by_broker??"");setAgreedOn(deal?.agreed_on?String(deal.agreed_on).slice(0,10):new Date().toISOString().slice(0,10));setNotes(deal?.notes??"");setMsg(null);setEditing(true)};
 const save=async()=>{const problem=validateSplit(boreal,broker,terms);if(problem){setMsg(problem);return}setSaving(true);setMsg(null);try{const res=await rawApiFetch(`/api/broker-imports/deal/${encodeURIComponent(applicationId)}`,{method:"PUT",body:JSON.stringify({boreal_pct:boreal.trim()===""?null:Number(boreal),broker_pct:broker.trim()===""?null:Number(broker),terms,agreed_by_broker:agreedBy,agreed_on:agreedOn,notes})});const j:any=await res.json().catch(()=>({}));if(!res.ok){setMsg(j?.message??j?.error??"Save failed.");return}setDeal((j?.data?.deal??j?.deal??null) as BrokerDeal|null);setEditing(false)}catch{setMsg("Save failed.")}finally{setSaving(false)}};
 if(!loaded)return null; const summary=splitText(deal,brokerName); const box={marginTop:8,padding:"10px 12px",borderRadius:6,fontSize:13,maxWidth:560} as const; const input={padding:"6px 8px",border:"1px solid var(--border, #d1d5db)",borderRadius:6,fontSize:13} as const;
 if(!editing)return <div data-testid="broker-deal-panel" style={{...box,background:deal?"#ecfdf5":"#fef2f2",color:deal?"#065f46":"#991b1b"}}>{deal?<span>Commission split with {brokerName}: <strong>{summary}</strong>{deal.agreed_by_broker?` - agreed by ${deal.agreed_by_broker}`:""}{deal.agreed_on?` on ${String(deal.agreed_on).slice(0,10)}`:""}</span>:<span>This file came from <strong>{brokerName}</strong>. Record the commission split before sending it to lenders.</span>}{canEdit&&<button type="button" data-testid="broker-deal-edit" onClick={startEdit} style={{marginLeft:10}}>{deal?"Change":"Record split"}</button>}</div>;
 const complement=(value:string,setOther:(v:string)=>void)=>{const n=Number(value);if(value.trim()!==""&&Number.isFinite(n)&&n>=0&&n<=100)setOther(String(Math.round((100-n)*100)/100))};
 return <div data-testid="broker-deal-form" style={{...box,display:"grid",gap:8,border:"1px solid var(--border, #d1d5db)"}}><strong>Commission split with {brokerName}</strong><div><label>Boreal % <input style={{...input,width:70}} inputMode="decimal" value={boreal} onChange={e=>{setBoreal(e.target.value);complement(e.target.value,setBroker)}}/></label> <label>{brokerName} % <input style={{...input,width:70}} inputMode="decimal" value={broker} onChange={e=>{setBroker(e.target.value);complement(e.target.value,setBoreal)}}/></label></div><label>Or other agreed terms <input style={{...input,width:"100%"}} value={terms} onChange={e=>setTerms(e.target.value)} placeholder="e.g. flat $2,500 to broker on funding"/></label><div><label>Agreed by (at {brokerName}) <input style={input} value={agreedBy} onChange={e=>setAgreedBy(e.target.value)}/></label> <label>Date agreed <input style={input} type="date" value={agreedOn} onChange={e=>setAgreedOn(e.target.value)}/></label></div><label>Notes <input style={{...input,width:"100%"}} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{msg&&<div role="alert" style={{color:"#991b1b"}}>{msg}</div>}<div><button type="button" data-testid="broker-deal-save" disabled={saving} onClick={save}>{saving?"Saving...":"Save split"}</button> <button type="button" onClick={()=>setEditing(false)}>Cancel</button></div></div>;
}
