import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from "react";
import Input from "@/components/ui/Input";
import Select from "@/components/ui/Select";
import ConversationItem from "./ConversationItem";
const ConversationList = ({ conversations, selectedConversationId, filters, onFiltersChange, onSelectConversation }) => {
    const staffOptions = useMemo(() => Array.from(new Set(conversations.map((conv) => conv.assignedTo).filter(Boolean))), [conversations]);
    return (_jsxs("div", { className: "flex flex-col h-full", children: [_jsxs("div", { className: "grid grid-cols-2 gap-2 mb-2", children: [_jsxs(Select, { label: "Channel", value: filters.channel, onChange: (e) => onFiltersChange({ channel: e.target.value }), children: [_jsx("option", { value: "all", children: "All" }), _jsx("option", { value: "chat", children: "Chat" }), _jsx("option", { value: "human", children: "Talk to Human" }), _jsx("option", { value: "issue", children: "Issue" }), _jsx("option", { value: "sms", children: "SMS" }), _jsx("option", { value: "system", children: "System" }), _jsx("option", { value: "credit_readiness", children: "Credit Readiness" }), _jsx("option", { value: "contact_form", children: "Contact Form" })] }), _jsxs(Select, { label: "Silo", value: filters.silo, onChange: (e) => onFiltersChange({ silo: e.target.value }), children: [_jsx("option", { value: "all", children: "All Silos" }), _jsx("option", { value: "BF", children: "BF" }), _jsx("option", { value: "BI", children: "BI" }), _jsx("option", { value: "SLF", children: "SLF" })] }), _jsxs(Select, { label: "Assigned", value: filters.assigned, onChange: (e) => onFiltersChange({ assigned: e.target.value }), children: [_jsx("option", { value: "all", children: "Anyone" }), staffOptions.map((staff) => (_jsx("option", { value: staff, children: staff }, staff)))] }), _jsx(Input, { label: "Search", placeholder: "Name or application ID", value: filters.search, onChange: (e) => onFiltersChange({ search: e.target.value }) })] }), _jsxs("div", { className: "overflow-y-auto flex-1", "data-testid": "conversation-list", children: [conversations.map((conversation) => (_jsx(ConversationItem, { conversation: conversation, selected: conversation.id === selectedConversationId, onSelect: onSelectConversation }, conversation.id))), !conversations.length && _jsx("div", { className: "text-sm text-slate-500", children: "No conversations match filters." })] })] }));
};
export default ConversationList;
