// BF_PORTAL_SHARED_DATETIME_PICKER_v1
// Extracted VERBATIM from components/tasks/TaskModal.tsx so the CRM Meeting popup
// uses the SAME picker as the Task popup instead of two raw datetime-local inputs.
// TaskModal imports this too, so there is no second copy left to drift.
import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";

const ctl: CSSProperties = { background: "var(--ui-surface-strong)", color: "var(--ui-text)", border: "1px solid var(--ui-border)", borderRadius: 8, padding: "5px 8px", fontSize: 13 };

export default function DateTimePicker({ value, onChange }: { value: string; onChange: (iso: string) => void }) {
  const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null); const selected = value ? new Date(value) : null;
  const [viewMonth, setViewMonth] = useState(() => (selected ? new Date(selected.getFullYear(), selected.getMonth(), 1) : new Date(new Date().getFullYear(), new Date().getMonth(), 1)));
  useEffect(() => { const onDoc = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false); }; document.addEventListener("mousedown", onDoc); return () => document.removeEventListener("mousedown", onDoc); }, []);
  const label = selected ? selected.toLocaleString([], { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "Set date & time";
  const setDatePart = (day: Date) => { const base = selected ?? new Date(new Date().setHours(9, 0, 0, 0)); onChange(new Date(day.getFullYear(), day.getMonth(), day.getDate(), base.getHours(), base.getMinutes(), 0, 0).toISOString()); };
  const setTimePart = (hh: number, mm: number) => { const base = selected ?? new Date(); onChange(new Date(base.getFullYear(), base.getMonth(), base.getDate(), hh, mm, 0, 0).toISOString()); };
  const monthDays = useMemo(() => { const first = new Date(viewMonth.getFullYear(), viewMonth.getMonth(), 1); const cells: (Date | null)[] = []; for (let i = 0; i < first.getDay(); i += 1) cells.push(null); for (let d = 1; d <= new Date(viewMonth.getFullYear(), viewMonth.getMonth() + 1, 0).getDate(); d += 1) cells.push(new Date(viewMonth.getFullYear(), viewMonth.getMonth(), d)); return cells; }, [viewMonth]);
  const times = [] as { label: string; hh: number; mm: number }[]; for (let h = 7; h <= 19; h += 1) for (const m of [0, 30]) { const d = new Date(); d.setHours(h, m, 0, 0); times.push({ label: d.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }), hh: h, mm: m }); }
  const sameDay = (a: Date, b: Date) => a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
  return <div ref={ref} style={{ position: "relative" }}><button type="button" onClick={() => setOpen((v) => !v)} style={{ ...ctl, width: "100%", textAlign: "left", cursor: "pointer" }}>{label}</button>{open && <div style={{ position: "absolute", zIndex: 60, top: "calc(100% + 4px)", left: 0, display: "flex", gap: 8, background: "var(--ui-surface, #fff)", border: "1px solid var(--ui-border)", borderRadius: 10, padding: 10, boxShadow: "0 8px 24px rgba(0,0,0,0.2)" }}><div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}><button type="button" onClick={() => setViewMonth(new Date(viewMonth.getFullYear(), viewMonth.getMonth() - 1, 1))} style={{ ...ctl, padding: "2px 8px", cursor: "pointer" }}>{"<"}</button><strong style={{ fontSize: 13 }}>{viewMonth.toLocaleString([], { month: "long", year: "numeric" })}</strong><button type="button" onClick={() => setViewMonth(new Date(viewMonth.getFullYear(), viewMonth.getMonth() + 1, 1))} style={{ ...ctl, padding: "2px 8px", cursor: "pointer" }}>{">"}</button></div><div style={{ display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 2 }}>{["S", "M", "T", "W", "T", "F", "S"].map((d, i) => <div key={i} style={{ textAlign: "center", fontSize: 11, color: "var(--ui-text-muted)" }}>{d}</div>)}{monthDays.map((d, i) => <button key={i} type="button" disabled={!d} onClick={() => d && setDatePart(d)} style={{ width: 28, height: 28, borderRadius: 6, fontSize: 12, cursor: d ? "pointer" : "default", border: d && selected && sameDay(d, selected) ? "1px solid var(--ui-accent-blue)" : "1px solid transparent", background: d && selected && sameDay(d, selected) ? "var(--ui-accent-blue)" : "transparent", color: d && selected && sameDay(d, selected) ? "#fff" : "var(--ui-text)" }}>{d ? d.getDate() : ""}</button>)}</div><div style={{ display: "flex", justifyContent: "space-between", marginTop: 6 }}><button type="button" onClick={() => { onChange(""); setOpen(false); }} style={{ ...ctl, padding: "2px 8px", cursor: "pointer" }}>Clear</button><button type="button" onClick={() => setDatePart(new Date())} style={{ ...ctl, padding: "2px 8px", cursor: "pointer" }}>Today</button></div></div><div style={{ width: 92, maxHeight: 232, overflowY: "auto" }}>{times.map((t) => { const isSel = selected && selected.getHours() === t.hh && selected.getMinutes() === t.mm; return <button key={t.label} type="button" onClick={() => setTimePart(t.hh, t.mm)} style={{ display: "block", width: "100%", textAlign: "center", padding: "5px 0", fontSize: 12, borderRadius: 6, cursor: "pointer", border: "1px solid transparent", background: isSel ? "var(--ui-accent-blue)" : "transparent", color: isSel ? "#fff" : "var(--ui-text)" }}>{t.label}</button>; })}</div></div>}</div>;
}
